site_name: UnBuscas 

theme:
  name: material
  language: "pt"
  logo: assets/logo.svg
  palette:
    primary: deep purple
    accent: indigo
  features:
    - navigation.tabs

nav:
- Inicio: index.md
- Escopo: Documento de escopo do Produto.md
- Visão: Visão do Produto e do Projeto - Centauri Versao-2.md
- Arquitetura: Documento de Arquitetura - Centauri - MDS-2023.2.md
- Atas de Reunião: atasReuniao.md