# fly.toml app configuration file generated for backend-meili on 2023-12-05T22:05:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-meili"
primary_region = "gru"

[http_service]
  internal_port = 7700
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
